// -----------------------------------------------------------------------------
// This file was autogenerated by symforce. Do NOT modify by hand.
// -----------------------------------------------------------------------------
#pragma once

#include <array>

#include "./storage_ops.h"


namespace codegen_test_cpp_ns {

class states_t {
 public:
  std::array<double, 2> p{};
};

}  // namespace codegen_test_cpp_ns

// Include StorageOps specialization
#include "./storage_ops/states_t.h"
