#  -----------------------------------------------------------------------------
# This file was autogenerated by symforce. Do NOT modify by hand.
#
# Instead modify:
#     symforce/codegen/python/templates/geo_package/example/geo_package_python_test.py.jinja
#
# And then run `symforce_geo_codegen_test --update`.
# -----------------------------------------------------------------------------
"""
Tests for Python runtime geometry types. Mostly checking basic generation logic
since the math is tested comprehensively in symbolic form.
"""

# TODO improve this to match geo_test.cc

# Add the generated package to the path
import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

import geo  # type: ignore


def main():
    rot = geo.Rot3()

    print(rot)
    vec = rot.to_storage()
    print(vec)
    rot2 = geo.Rot3.from_storage(vec)
    assert rot.data == rot2.data

    pose = geo.Pose3.from_tangent(range(6))
    print(pose)
    print(pose.inverse())
    print(pose.to_tangent())
    print(geo.Pose3.from_tangent(pose.to_tangent()))


if __name__ == "__main__":
    main()
