# ----------------------------------------------------------------------------
# SymForce - Copyright 2025, Skydio, Inc.
# This source code is under the Apache 2.0 license found in the LICENSE file.
# ----------------------------------------------------------------------------

import symforce

symforce.set_epsilon_to_number()

from pathlib import Path

import symforce.symbolic as sf
from symforce import caspar
from symforce import path_util
from symforce import typing as T
from symforce.caspar import CasparLibrary
from symforce.caspar import memory as mem
from symforce.caspar.memory import DType
from symforce.codegen.format_util import format_cpp
from symforce.test_util import TestCase
from symforce.test_util import symengine_only

TEST_DATA_DIR = (
    path_util.symforce_data_root(__file__)
    / "test"
    / "symforce_function_codegen_test_data"
    / symforce.get_symbolic_api()
    / "symforce_caspar_codegen_test"
)

SOLVER_TEST_DATA_DIR = (
    path_util.symforce_data_root(__file__)
    / "test"
    / "symforce_function_codegen_test_data"
    / symforce.get_symbolic_api()
    / "symforce_caspar_solver_test"
)

KERNEL_FILENAMES = (
    "kernel_caspar_padding_lane_score.cu",
    "kernel_caspar_padding_lane_score.h",
)


def _make_padding_lane_library() -> CasparLibrary:
    """
    Shaped like the OpenCV reprojection factor from symforce-org/symforce#469, whose score kernel
    LLVM miscompiles without zero-initialized registers.  Simpler kernels don't reproduce it.
    """
    caslib = CasparLibrary()

    @caslib.add_factor
    def caspar_padding_lane(
        cam_T_world: T.Annotated[sf.Pose3, mem.TunableShared],
        point: T.Annotated[sf.V3, mem.TunableShared],
        calibration: T.Annotated[sf.V8, mem.TunableShared],
        pixel: T.Annotated[sf.V2, mem.ConstantSequential],
    ) -> sf.V2:
        fx, fy, cx, cy, k1, k2, p1, p2 = calibration

        point_cam = cam_T_world * point
        xn = point_cam[0] / point_cam[2]
        yn = point_cam[1] / point_cam[2]

        r2 = xn * xn + yn * yn
        radial = 1 + k1 * r2 + k2 * r2 * r2
        x_d = xn * radial + 2 * p1 * xn * yn + p2 * (r2 + 2 * xn * xn)
        y_d = yn * radial + p1 * (r2 + 2 * yn * yn) + 2 * p2 * xn * yn

        return sf.V2(fx * x_d + cx, fy * y_d + cy) - pixel

    return caslib


def _make_solver_library() -> CasparLibrary:
    """
    Rosenbrock converges slowly, so a solve is still progressing after a few iterations.
    """
    caslib = CasparLibrary(dtype=DType.DOUBLE)

    @caslib.add_factor
    def rosenbrock(
        x: T.Annotated[sf.V2, mem.TunableShared],
    ) -> sf.V2:
        return sf.V2(10 * (x[1] - x[0] * x[0]), 1 - x[0])

    return caslib


class SymforceCasparCodegenTest(TestCase):
    """
    Tests the CUDA kernels generated by caspar.
    """

    @symengine_only
    def test_generate_padding_lane_kernel(self) -> None:
        """
        Keep the kernel caspar_padding_lane_cuda_test.cc runs up to date.
        """
        output_dir = self.make_output_dir("sf_caspar_padding_lane_")
        _make_padding_lane_library().generate(output_dir, python_bindings=False)

        kernel_dir = output_dir / "kernel"
        kernel_dir.mkdir()
        for name in KERNEL_FILENAMES:
            # Format against the checked-in path, to pick up SymForce's clang-format config.
            content = (output_dir / name).read_text()
            (kernel_dir / name).write_text(format_cpp(content, str(TEST_DATA_DIR / name)))

        self.compare_or_update_directory(kernel_dir, TEST_DATA_DIR)

    @symengine_only
    def test_generate_solver(self) -> None:
        """
        Keep the solver caspar_solver_cuda_test.cc runs up to date.
        """
        output_dir = self.make_output_dir("sf_caspar_solver_")
        _make_solver_library().generate(output_dir, python_bindings=False)

        # The runtime is compiled from its own directory; check in only what was generated.
        runtime_dir = Path(caspar.__file__).parent / "source" / "runtime"
        generated_dir = output_dir / "generated"
        generated_dir.mkdir()
        for path in sorted(output_dir.glob("*")):
            if (
                path.suffix not in {".cu", ".cc", ".h", ".cuh"}
                or (runtime_dir / path.name).exists()
            ):
                continue
            (generated_dir / path.name).write_text(
                format_cpp(path.read_text(), str(SOLVER_TEST_DATA_DIR / path.name))
            )

        self.compare_or_update_directory(generated_dir, SOLVER_TEST_DATA_DIR)


if __name__ == "__main__":
    SymforceCasparCodegenTest.main()
