/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __codegen_test_cpp_values_vec_t_hpp__
#define __codegen_test_cpp_values_vec_t_hpp__

#include <lcm/lcm_coretypes.h>


namespace codegen_test_cpp
{

class values_vec_t
{
    public:
        double     x;

        double     y;

        double     rot[4];

        double     rot_vec[3][4];

        double     scalar_vec[3];

        double     list_of_lists[3][3][4];

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "values_vec_t"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int values_vec_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int values_vec_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int values_vec_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t values_vec_t::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* values_vec_t::getTypeName()
{
    return "values_vec_t";
}

int values_vec_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->x, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->y, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->rot[0], 4);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < 3; a0++) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->rot_vec[a0][0], 4);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->scalar_vec[0], 3);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < 3; a0++) {
        for (int a1 = 0; a1 < 3; a1++) {
            tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->list_of_lists[a0][a1][0], 4);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    return pos;
}

int values_vec_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->x, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->y, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->rot[0], 4);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < 3; a0++) {
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->rot_vec[a0][0], 4);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->scalar_vec[0], 3);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < 3; a0++) {
        for (int a1 = 0; a1 < 3; a1++) {
            tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->list_of_lists[a0][a1][0], 4);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    return pos;
}

int values_vec_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 4);
    enc_size += 3 * __double_encoded_array_size(NULL, 4);
    enc_size += __double_encoded_array_size(NULL, 3);
    enc_size += 3 * 3 * __double_encoded_array_size(NULL, 4);
    return enc_size;
}

uint64_t values_vec_t::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0xa16b5be908bd71cfLL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
