// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.ts.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

type Vector3 = [number, number, number];
type Matrix33 = [[number, number, number], [number, number, number], [number, number, number]];

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: vector_multiply
 *
 * Args:
 *     mat33: Matrix33
 *     vec3: Matrix31
 *
 * Outputs:
 *     res: Matrix31
 */
export function vectorMultiply(mat33: number[][], vec3: number[]): Vector3 {
  // Total ops: 15

  // Output terms (1)
  const _res: Vector3 = [0, 0, 0];
  _res[0] = mat33[0][0] * vec3[0] + mat33[0][1] * vec3[1] + mat33[0][2] * vec3[2];
  _res[1] = mat33[1][0] * vec3[0] + mat33[1][1] * vec3[1] + mat33[1][2] * vec3[2];
  _res[2] = mat33[2][0] * vec3[0] + mat33[2][1] * vec3[1] + mat33[2][2] * vec3[2];

  return _res;
}
