// -----------------------------------------------------------------------------
// This file was autogenerated by symforce. Do NOT modify by hand.
// -----------------------------------------------------------------------------
#pragma once

#include <array>

#include "./storage_ops.h"


namespace codegen_multi_function {

class inputs_states_t {
 public:
  std::array<double, 2> p{};
};

}  // namespace codegen_multi_function

// Include StorageOps specialization
#include "./storage_ops/inputs_states_t.h"
