// -----------------------------------------------------------------------------
// This file was autogenerated by symforce. Do NOT modify by hand.
// -----------------------------------------------------------------------------
#pragma once

#include <array>

#include "./storage_ops.h"


namespace codegen_multi_function {

class outputs_2_t {
 public:
  double foo{};
};

}  // namespace codegen_multi_function

// Include StorageOps specialization
#include "./storage_ops/outputs_2_t.h"
