# -----------------------------------------------------------------------------
# This file was autogenerated by symforce. Do NOT modify by hand.
# -----------------------------------------------------------------------------
"""
Python StorageOps implementation for types in "codegen_test_python".
"""

from . import constants_t
from . import states_t


def register(types_package):
    constants_t.register(types_package.constants_t)
    states_t.register(types_package.states_t)
