// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

#include <sym/pose3.h>

namespace sym {

/**
 * Composition of two elements in the group.
 *
 * Returns:
 *     Element: a @ b
 *     res_D_a: (6x6) jacobian of res (6) wrt arg a (6)
 *     res_D_b: (6x6) jacobian of res (6) wrt arg b (6)
 */
template <typename Scalar>
sym::Pose3<Scalar> ComposePose3WithJacobians(const sym::Pose3<Scalar>& a,
                                             const sym::Pose3<Scalar>& b,
                                             Eigen::Matrix<Scalar, 6, 6>* const res_D_a = nullptr,
                                             Eigen::Matrix<Scalar, 6, 6>* const res_D_b = nullptr) {
  // Total ops: 328

  // Input arrays
  const Eigen::Matrix<Scalar, 7, 1>& _a = a.Data();
  const Eigen::Matrix<Scalar, 7, 1>& _b = b.Data();

  // Intermediate terms (132)
  const Scalar _tmp0 = _a[2] * _b[1];
  const Scalar _tmp1 = _a[0] * _b[3];
  const Scalar _tmp2 = _a[1] * _b[2];
  const Scalar _tmp3 = _a[3] * _b[0];
  const Scalar _tmp4 = -_tmp0 + _tmp1 + _tmp2 + _tmp3;
  const Scalar _tmp5 = _a[3] * _b[1];
  const Scalar _tmp6 = _a[1] * _b[3];
  const Scalar _tmp7 = _a[0] * _b[2];
  const Scalar _tmp8 = _a[2] * _b[0];
  const Scalar _tmp9 = _tmp5 + _tmp6 - _tmp7 + _tmp8;
  const Scalar _tmp10 = _a[0] * _b[1];
  const Scalar _tmp11 = _a[2] * _b[3];
  const Scalar _tmp12 = _a[3] * _b[2];
  const Scalar _tmp13 = _a[1] * _b[0];
  const Scalar _tmp14 = _tmp10 + _tmp11 + _tmp12 - _tmp13;
  const Scalar _tmp15 = _a[1] * _b[1];
  const Scalar _tmp16 = _a[2] * _b[2];
  const Scalar _tmp17 = _a[0] * _b[0];
  const Scalar _tmp18 = _a[3] * _b[3];
  const Scalar _tmp19 = -_tmp15 - _tmp16 - _tmp17 + _tmp18;
  const Scalar _tmp20 = std::pow(_a[2], Scalar(2));
  const Scalar _tmp21 = -2 * _tmp20;
  const Scalar _tmp22 = std::pow(_a[1], Scalar(2));
  const Scalar _tmp23 = -2 * _tmp22;
  const Scalar _tmp24 = _tmp21 + _tmp23 + 1;
  const Scalar _tmp25 = 2 * _a[0];
  const Scalar _tmp26 = _a[2] * _tmp25;
  const Scalar _tmp27 = 2 * _a[3];
  const Scalar _tmp28 = _a[1] * _tmp27;
  const Scalar _tmp29 = _tmp26 + _tmp28;
  const Scalar _tmp30 = _a[1] * _tmp25;
  const Scalar _tmp31 = _a[2] * _tmp27;
  const Scalar _tmp32 = -_tmp31;
  const Scalar _tmp33 = _tmp30 + _tmp32;
  const Scalar _tmp34 = std::pow(_a[0], Scalar(2));
  const Scalar _tmp35 = 1 - 2 * _tmp34;
  const Scalar _tmp36 = _tmp21 + _tmp35;
  const Scalar _tmp37 = 2 * _a[1] * _a[2];
  const Scalar _tmp38 = _a[0] * _tmp27;
  const Scalar _tmp39 = -_tmp38;
  const Scalar _tmp40 = _tmp37 + _tmp39;
  const Scalar _tmp41 = _tmp30 + _tmp31;
  const Scalar _tmp42 = _tmp23 + _tmp35;
  const Scalar _tmp43 = _tmp37 + _tmp38;
  const Scalar _tmp44 = -_tmp28;
  const Scalar _tmp45 = _tmp26 + _tmp44;
  const Scalar _tmp46 = (Scalar(1) / Scalar(2)) * _tmp10;
  const Scalar _tmp47 = -_tmp46;
  const Scalar _tmp48 = (Scalar(1) / Scalar(2)) * _tmp11;
  const Scalar _tmp49 = (Scalar(1) / Scalar(2)) * _tmp12;
  const Scalar _tmp50 = -_tmp49;
  const Scalar _tmp51 = (Scalar(1) / Scalar(2)) * _tmp13;
  const Scalar _tmp52 = -_tmp51;
  const Scalar _tmp53 = _tmp50 + _tmp52;
  const Scalar _tmp54 = _tmp47 + _tmp48 + _tmp53;
  const Scalar _tmp55 = 2 * _tmp14;
  const Scalar _tmp56 = (Scalar(1) / Scalar(2)) * _tmp6;
  const Scalar _tmp57 = -_tmp56;
  const Scalar _tmp58 = (Scalar(1) / Scalar(2)) * _tmp5;
  const Scalar _tmp59 = (Scalar(1) / Scalar(2)) * _tmp7;
  const Scalar _tmp60 = -_tmp59;
  const Scalar _tmp61 = (Scalar(1) / Scalar(2)) * _tmp8;
  const Scalar _tmp62 = -_tmp61;
  const Scalar _tmp63 = _tmp60 + _tmp62;
  const Scalar _tmp64 = _tmp57 + _tmp58 + _tmp63;
  const Scalar _tmp65 = 2 * _tmp9;
  const Scalar _tmp66 = (Scalar(1) / Scalar(2)) * _tmp1;
  const Scalar _tmp67 = -_tmp66;
  const Scalar _tmp68 = (Scalar(1) / Scalar(2)) * _tmp3;
  const Scalar _tmp69 = -_tmp68;
  const Scalar _tmp70 = _tmp67 + _tmp69;
  const Scalar _tmp71 = (Scalar(1) / Scalar(2)) * _tmp0;
  const Scalar _tmp72 = -_tmp71;
  const Scalar _tmp73 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp74 = _tmp72 + _tmp73;
  const Scalar _tmp75 = _tmp70 + _tmp74;
  const Scalar _tmp76 = 2 * _tmp4;
  const Scalar _tmp77 = (Scalar(1) / Scalar(2)) * _tmp15;
  const Scalar _tmp78 = (Scalar(1) / Scalar(2)) * _tmp16;
  const Scalar _tmp79 = (Scalar(1) / Scalar(2)) * _tmp18;
  const Scalar _tmp80 = (Scalar(1) / Scalar(2)) * _tmp17;
  const Scalar _tmp81 = _tmp79 - _tmp80;
  const Scalar _tmp82 = _tmp77 + _tmp78 + _tmp81;
  const Scalar _tmp83 = 2 * _tmp19;
  const Scalar _tmp84 = -_tmp30;
  const Scalar _tmp85 = -_tmp22;
  const Scalar _tmp86 = _tmp34 + _tmp85;
  const Scalar _tmp87 = std::pow(_a[3], Scalar(2));
  const Scalar _tmp88 = -_tmp87;
  const Scalar _tmp89 = _tmp20 + _tmp88;
  const Scalar _tmp90 = -_tmp34;
  const Scalar _tmp91 = -_tmp37;
  const Scalar _tmp92 = -_tmp77;
  const Scalar _tmp93 = _tmp79 + _tmp80;
  const Scalar _tmp94 = _tmp78 + _tmp92 + _tmp93;
  const Scalar _tmp95 = -_tmp73;
  const Scalar _tmp96 = _tmp72 + _tmp95;
  const Scalar _tmp97 = _tmp66 + _tmp69 + _tmp96;
  const Scalar _tmp98 = -_tmp58;
  const Scalar _tmp99 = _tmp57 + _tmp98;
  const Scalar _tmp100 = _tmp60 + _tmp61;
  const Scalar _tmp101 = _tmp100 + _tmp99;
  const Scalar _tmp102 = -_tmp48;
  const Scalar _tmp103 = _tmp102 + _tmp47;
  const Scalar _tmp104 = _tmp49 + _tmp52;
  const Scalar _tmp105 = _tmp103 + _tmp104;
  const Scalar _tmp106 = -_tmp20;
  const Scalar _tmp107 = _tmp106 + _tmp87;
  const Scalar _tmp108 = -_tmp26;
  const Scalar _tmp109 = _tmp67 + _tmp68 + _tmp96;
  const Scalar _tmp110 = -_tmp78;
  const Scalar _tmp111 = _tmp110 + _tmp77 + _tmp93;
  const Scalar _tmp112 = _tmp102 + _tmp46 + _tmp53;
  const Scalar _tmp113 = _tmp56 + _tmp63 + _tmp98;
  const Scalar _tmp114 = _tmp22 + _tmp90;
  const Scalar _tmp115 = _tmp104 + _tmp46 + _tmp48;
  const Scalar _tmp116 = _tmp70 + _tmp71 + _tmp95;
  const Scalar _tmp117 = -_tmp116 * _tmp76;
  const Scalar _tmp118 = _tmp59 + _tmp62 + _tmp99;
  const Scalar _tmp119 = _tmp110 + _tmp81 + _tmp92;
  const Scalar _tmp120 = _tmp119 * _tmp83;
  const Scalar _tmp121 = -_tmp118 * _tmp65 + _tmp120;
  const Scalar _tmp122 = _tmp119 * _tmp55;
  const Scalar _tmp123 = _tmp118 * _tmp76;
  const Scalar _tmp124 = _tmp116 * _tmp55;
  const Scalar _tmp125 = _tmp119 * _tmp65;
  const Scalar _tmp126 = _tmp66 + _tmp68 + _tmp74;
  const Scalar _tmp127 = _tmp103 + _tmp50 + _tmp51;
  const Scalar _tmp128 = -_tmp127 * _tmp55;
  const Scalar _tmp129 = _tmp127 * _tmp65;
  const Scalar _tmp130 = _tmp119 * _tmp76;
  const Scalar _tmp131 = _tmp100 + _tmp56 + _tmp58;

  // Output terms (3)
  Eigen::Matrix<Scalar, 7, 1> _res;

  _res[0] = _tmp4;
  _res[1] = _tmp9;
  _res[2] = _tmp14;
  _res[3] = _tmp19;
  _res[4] = _a[4] + _b[4] * _tmp24 + _b[5] * _tmp33 + _b[6] * _tmp29;
  _res[5] = _a[5] + _b[4] * _tmp41 + _b[5] * _tmp36 + _b[6] * _tmp40;
  _res[6] = _a[6] + _b[4] * _tmp45 + _b[5] * _tmp43 + _b[6] * _tmp42;

  if (res_D_a != nullptr) {
    Eigen::Matrix<Scalar, 6, 6>& _res_D_a = (*res_D_a);

    _res_D_a(0, 0) = _tmp54 * _tmp55 - _tmp64 * _tmp65 - _tmp75 * _tmp76 + _tmp82 * _tmp83;
    _res_D_a(1, 0) = _tmp54 * _tmp83 - _tmp55 * _tmp82 + _tmp64 * _tmp76 - _tmp65 * _tmp75;
    _res_D_a(2, 0) = -_tmp54 * _tmp76 - _tmp55 * _tmp75 + _tmp64 * _tmp83 + _tmp65 * _tmp82;
    _res_D_a(3, 0) = _b[5] * _tmp29 + _b[6] * (_tmp31 + _tmp84);
    _res_D_a(4, 0) = _b[5] * _tmp40 + _b[6] * (_tmp86 + _tmp89);
    _res_D_a(5, 0) = _b[5] * (_tmp20 + _tmp85 + _tmp87 + _tmp90) + _b[6] * (_tmp39 + _tmp91);
    _res_D_a(0, 1) = -_tmp101 * _tmp76 + _tmp105 * _tmp83 + _tmp55 * _tmp94 - _tmp65 * _tmp97;
    _res_D_a(1, 1) = -_tmp101 * _tmp65 - _tmp105 * _tmp55 + _tmp76 * _tmp97 + _tmp83 * _tmp94;
    _res_D_a(2, 1) = -_tmp101 * _tmp55 + _tmp105 * _tmp65 - _tmp76 * _tmp94 + _tmp83 * _tmp97;
    _res_D_a(3, 1) = _b[4] * (_tmp108 + _tmp44) + _b[6] * (_tmp107 + _tmp86);
    _res_D_a(4, 1) = _b[4] * (_tmp38 + _tmp91) + _b[6] * _tmp41;
    _res_D_a(5, 1) = _b[4] * (_tmp106 + _tmp22 + _tmp34 + _tmp88) + _b[6] * _tmp45;
    _res_D_a(0, 2) = _tmp109 * _tmp55 - _tmp111 * _tmp65 - _tmp112 * _tmp76 + _tmp113 * _tmp83;
    _res_D_a(1, 2) = _tmp109 * _tmp83 + _tmp111 * _tmp76 - _tmp112 * _tmp65 - _tmp113 * _tmp55;
    _res_D_a(2, 2) = -_tmp109 * _tmp76 + _tmp111 * _tmp83 - _tmp112 * _tmp55 + _tmp113 * _tmp65;
    _res_D_a(3, 2) = _b[4] * _tmp33 + _b[5] * (_tmp114 + _tmp89);
    _res_D_a(4, 2) = _b[4] * (_tmp107 + _tmp114) + _b[5] * (_tmp32 + _tmp84);
    _res_D_a(5, 2) = _b[4] * _tmp43 + _b[5] * (_tmp108 + _tmp28);
    _res_D_a(0, 3) = 0;
    _res_D_a(1, 3) = 0;
    _res_D_a(2, 3) = 0;
    _res_D_a(3, 3) = 1;
    _res_D_a(4, 3) = 0;
    _res_D_a(5, 3) = 0;
    _res_D_a(0, 4) = 0;
    _res_D_a(1, 4) = 0;
    _res_D_a(2, 4) = 0;
    _res_D_a(3, 4) = 0;
    _res_D_a(4, 4) = 1;
    _res_D_a(5, 4) = 0;
    _res_D_a(0, 5) = 0;
    _res_D_a(1, 5) = 0;
    _res_D_a(2, 5) = 0;
    _res_D_a(3, 5) = 0;
    _res_D_a(4, 5) = 0;
    _res_D_a(5, 5) = 1;
  }

  if (res_D_b != nullptr) {
    Eigen::Matrix<Scalar, 6, 6>& _res_D_b = (*res_D_b);

    _res_D_b(0, 0) = _tmp115 * _tmp55 + _tmp117 + _tmp121;
    _res_D_b(1, 0) = _tmp115 * _tmp83 - _tmp116 * _tmp65 - _tmp122 + _tmp123;
    _res_D_b(2, 0) = -_tmp115 * _tmp76 + _tmp118 * _tmp83 - _tmp124 + _tmp125;
    _res_D_b(3, 0) = 0;
    _res_D_b(4, 0) = 0;
    _res_D_b(5, 0) = 0;
    _res_D_b(0, 1) = _tmp122 - _tmp123 - _tmp126 * _tmp65 + _tmp127 * _tmp83;
    _res_D_b(1, 1) = _tmp121 + _tmp126 * _tmp76 + _tmp128;
    _res_D_b(2, 1) = -_tmp118 * _tmp55 + _tmp126 * _tmp83 + _tmp129 - _tmp130;
    _res_D_b(3, 1) = 0;
    _res_D_b(4, 1) = 0;
    _res_D_b(5, 1) = 0;
    _res_D_b(0, 2) = _tmp124 - _tmp125 - _tmp127 * _tmp76 + _tmp131 * _tmp83;
    _res_D_b(1, 2) = _tmp116 * _tmp83 - _tmp129 + _tmp130 - _tmp131 * _tmp55;
    _res_D_b(2, 2) = _tmp117 + _tmp120 + _tmp128 + _tmp131 * _tmp65;
    _res_D_b(3, 2) = 0;
    _res_D_b(4, 2) = 0;
    _res_D_b(5, 2) = 0;
    _res_D_b(0, 3) = 0;
    _res_D_b(1, 3) = 0;
    _res_D_b(2, 3) = 0;
    _res_D_b(3, 3) = _tmp24;
    _res_D_b(4, 3) = _tmp41;
    _res_D_b(5, 3) = _tmp45;
    _res_D_b(0, 4) = 0;
    _res_D_b(1, 4) = 0;
    _res_D_b(2, 4) = 0;
    _res_D_b(3, 4) = _tmp33;
    _res_D_b(4, 4) = _tmp36;
    _res_D_b(5, 4) = _tmp43;
    _res_D_b(0, 5) = 0;
    _res_D_b(1, 5) = 0;
    _res_D_b(2, 5) = 0;
    _res_D_b(3, 5) = _tmp29;
    _res_D_b(4, 5) = _tmp40;
    _res_D_b(5, 5) = _tmp42;
  }

  return sym::Pose3<Scalar>(_res);
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
