//  -----------------------------------------------------------------------------
// This file was autogenerated by symforce. Do NOT modify by hand.
// -----------------------------------------------------------------------------
/**
C++ StorageOps implementation for types in "codegen_test_cpp".
*/
#pragma once

#include <vector>

// Create default template traits that implement StorageOps. These will get specialized.
// TODO(hayk): Perhaps StorageOps should always live in the symforce namespace.
namespace codegen_test_cpp {
namespace StorageOps {

template<typename T>
size_t StorageDim() {
    return T::StorageDim();
};

template<typename T>
void ToStorage(const T& value, std::vector<double>* vec) {
    value.ToStorage(vec);
}

template<typename Container, typename T>
void FromStorage(const Container& elements, T* out) {
    T::FromStorage(elements, out);
}

}  // namespace StorageOps
}  // namespace codegen_test_cpp

// Include StorageOps specializations for each type
#include "./storage_ops/constants_t.h"
#include "./storage_ops/states_t.h"
