// ----------------------------------------------------------------------------
// This file was autogenerated by symforce. Do NOT modify by hand.
// ----------------------------------------------------------------------------
#pragma once

#include <cassert>
#include <vector>

namespace codegen_multi_function {
namespace StorageOps {

template<>
inline size_t StorageDim<inputs_states_t>() {
  return 2;
};

template<>
inline void ToStorage<inputs_states_t>(const inputs_states_t& value, std::vector<double>* vec) {
  assert(vec != nullptr);
  std::vector<double>& v = (*vec);
  v.resize(2);

  v[0] = value.p[0];
  v[1] = value.p[1];
}

template<typename Container>
void FromStorage(const Container& elements, inputs_states_t* out) {
  assert(out != nullptr);
  out->p[0] = elements[0];
  out->p[1] = elements[1];
}

}  // namespace StorageOps
}  // namespace codegen_multi_function
