//  -----------------------------------------------------------------------------
// This file was autogenerated by symforce. Do NOT modify by hand.
// -----------------------------------------------------------------------------
/**
C++ StorageOps concept. This template class is specialized per type.

See `symforce.ops.lie_group_ops` for details.
*/
#pragma once

#include <Eigen/Dense>

namespace geo {

template <typename T>
struct LieGroupOps {
  using Scalar = typename T::Scalar;

  static constexpr int32_t TangentDim();
  using TangentVec = Eigen::Matrix<Scalar, TangentDim(), 1>;

  static T FromTangent(const TangentVec& vec, const Scalar epsilon);
  static TangentVec ToTangent(const T& a, const Scalar epsilon);
  static T Retract(const T& a, const TangentVec& vec, const Scalar epsilon);
  static TangentVec LocalCoordinates(const T& a, const T& b, const Scalar epsilon);
};

}  // namespace geo
