# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     backends/python/templates/function/__init__.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

from .python_function import python_function
