# -----------------------------------------------------------------------------
# This file was autogenerated by symforce. Do NOT modify by hand.
# -----------------------------------------------------------------------------
"""
Defines operations for the type "states_t" to meet the StorageOps concept.
"""

STORAGE_DIM = 2


def to_storage(self):
    return [
        self.p[0],
        self.p[1],
    ]
    return elements

@classmethod
def from_storage(cls, elements):
    val = cls()
    val.p[0] = elements[0]
    val.p[1] = elements[1]
    return val


def register(storage_type):
    """
    Call on the type to register in these operations dynamically.

    Args:
        storage_type (states_t):
    """
    storage_type.STORAGE_DIM = STORAGE_DIM
    storage_type.to_storage = to_storage
    storage_type.from_storage = from_storage
