# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

import math  # pylint: disable=unused-import
import typing as T  # pylint: disable=unused-import

import numba
import numpy  # pylint: disable=unused-import

import sym  # pylint: disable=unused-import

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument


@numba.njit
def numba_test_func(x):
    # type: (numpy.ndarray) -> numpy.ndarray
    """
    This function was autogenerated from a symbolic function. Do not modify by hand.

    Symbolic function: numba_test_func

    Args:
        x: Matrix31

    Outputs:
        res: Matrix21
    """

    # Total ops: 0

    # Input arrays
    if not (x.shape == (3, 1) or x.shape == (3,)):
        raise IndexError("x is expected to have shape (3, 1) or (3,)")
    x = x.reshape((3, 1))

    # Intermediate terms (0)

    # Output terms
    _res = numpy.zeros((2, 1))
    _res[0, 0] = x[0, 0]
    _res[1, 0] = x[1, 0]
    return _res
