import math
import numba
import numpy
import typing as T

import sym  # pylint: disable=unused-import


@numba.njit
def numba_test_func(x):
    # type: (T.Sequence[float]) -> T.List[float]
    """
    This function was autogenerated from a symbolic function. Do not modify by hand.

    Symbolic function: numba_test_func

    Args:
        x: Matrix31

    Outputs:
        res: Matrix21

    """
    # Total ops: 0

    # Input arrays

    # Intermediate terms (0)

    # Output terms
    _res = [0.0] * 2
    _res[0] = x[0]
    _res[1] = x[1]
    return _res
