// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

#include <sym/pose3.h>

namespace sf_codegen_poses_list_cpp {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: poses_list_test_func
 *
 * Args:
 *     x: Matrix31
 *
 * Outputs:
 *     res: list
 */
template <typename Scalar>
std::array<sym::Pose3<Scalar>, 2> PosesListTestFunc(const Eigen::Matrix<Scalar, 3, 1>& x) {
  // Total ops: 0

  // Input arrays

  // Intermediate terms (0)

  // Output terms (1)
  std::array<sym::Pose3<Scalar>, 2> _res;

  _res[0].Data()[0] = 0;
  _res[0].Data()[1] = 0;
  _res[0].Data()[2] = 0;
  _res[0].Data()[3] = 1;
  _res[0].Data()[4] = x(0, 0);
  _res[0].Data()[5] = x(1, 0);
  _res[0].Data()[6] = x(2, 0);
  _res[1].Data()[0] = 0;
  _res[1].Data()[1] = 0;
  _res[1].Data()[2] = 0;
  _res[1].Data()[3] = 1;
  _res[1].Data()[4] = x(1, 0);
  _res[1].Data()[5] = x(2, 0);
  _res[1].Data()[6] = x(0, 0);

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sf_codegen_poses_list_cpp
